name: Build documentation site

on:
  push:
    branches:
      - master

jobs:
  mkdocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Run script
        run: bash .github/workflows/mkdocs/mkdocs.sh
        shell: bash
